version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ajv
    versions:
    - 7.0.3
    - 7.0.4
    - 7.1.0
    - 7.1.1
    - 7.2.1
    - 7.2.3
    - 8.0.1
    - 8.0.3
    - 8.0.5
    - 8.1.0
  - dependency-name: sinon
    versions:
    - 10.0.0
    - 10.0.1
  - dependency-name: mocha
    versions:
    - 8.3.0
    - 8.3.1
    - 8.3.2
  - dependency-name: marked
    versions:
    - 2.0.0
